--CREATE MEDICARE MEMBER INPUT FILE FOR DXCG


CREATE TEMP TABLE $SDM_DX_MC_ALLOWED_$ROMO_$YYYYMM
AS
SELECT UNIQ_PERSON_ID AS MEMBER_ID,
SUM(AMT_ALLOWED) AS ALLOWED
FROM ADH_SBX_ROSETTA..MEDICARE_CLM_$YYYYM1$DD
WHERE DENIED = 'N' 
AND DOS BETWEEN $START_DATE AND $END_DATE
AND CHECK_DT <= $RUN_OUT_DATE
GROUP BY UNIQ_PERSON_ID;

------------------------------------------

CREATE TABLE $SDM_GROUPER_DXCG_MEDICARE_MEMBER_INPUT_$ROMO_$YYYYMM
(
	MEMBER_ID CHARACTER (26),
	GENDER CHARACTER (1),
	DATE_OF_BIRTH CHARACTER (8),
	ELIGIBLE_MONTHS INTEGER,
	DIAGNOSIS_EXPENDITURE CHARACTER(10),
	MEDICAID_FLAG INTEGER,
	OREC INTEGER
)
DISTRIBUTE ON (MEMBER_ID, GENDER, DATE_OF_BIRTH, ELIGIBLE_MONTHS);

------------------------------------------

CREATE TEMP TABLE $SDM_MEDICARE_MEMBER_STAGE_$ROMO_$YYYYMM
AS
SELECT DISTINCT 
ME.UNIQ_PERSON_NUM AS MEMBER_ID,
ME.MEMBER_GENDER_CD ,
TO_CHAR(ME.MEMBER_BIRTH_DT,'YYYYMMDD') AS DOB,
ME.ELIG_START_DT,
ME.ELIG_END_DT,

CASE 
	WHEN ME.ELIG_START_DT BETWEEN $START_DATE AND $END_DATE
	AND  ME.ELIG_END_DT BETWEEN $START_DATE AND $END_DATE
	THEN (
		CASE WHEN TO_NUMBER(MONTHS_BETWEEN(ME.ELIG_END_DT,ME.ELIG_START_DT),'99') = 0 THEN 1
		ELSE ROUND(MONTHS_BETWEEN(ME.ELIG_END_DT,ME.ELIG_START_DT)) END
	     )
	WHEN ME.ELIG_START_DT BETWEEN $START_DATE AND $END_DATE
	AND	 ME.ELIG_END_DT > $END_DATE
	THEN (
		CASE WHEN TO_NUMBER(MONTHS_BETWEEN($END_DATE,ME.ELIG_START_DT),'99') = 0 THEN 1
		ELSE ROUND(MONTHS_BETWEEN($END_DATE,ME.ELIG_START_DT)) END
	     )
	WHEN ME.ELIG_END_DT BETWEEN $START_DATE AND $END_DATE
	AND  ME.ELIG_START_DT < $START_DATE
	THEN (
		CASE WHEN TO_NUMBER(MONTHS_BETWEEN(ME.ELIG_END_DT,$START_DATE), '99') = 0 THEN 1
		ELSE ROUND(MONTHS_BETWEEN(ME.ELIG_END_DT,$START_DATE)) END
	     )
	ELSE (
		CASE WHEN TO_NUMBER(MONTHS_BETWEEN($END_DATE,$START_DATE), '99') = 0 THEN 1
		ELSE ROUND(MONTHS_BETWEEN($END_DATE,$START_DATE)) END
	     )
END  AS MONTHS_ELIGIBLE,

CASE WHEN DA.ALLOWED IS NULL THEN 0  ELSE DA.ALLOWED END  AS ALLOWED,
CASE WHEN ME.MEDICAID_IND IN ('N', '',' ') THEN 0 ELSE 1 END AS MEDICAID,
CASE WHEN (ME.DISABLED_IND = 'Y' and ME.ESRD_IND = 'Y') THEN 3
                   WHEN (ME.DISABLED_IND = 'N' and ME.ESRD_IND = 'Y') THEN 2
                   WHEN (ME.DISABLED_IND = 'Y' and ME.ESRD_IND = 'N') THEN 1
                   ELSE 0 END AS OREC
FROM ADH_SBX_ROSETTA..MEDICARE_ELIG_$YYYYM1$DD AS ME --
LEFT JOIN $SDM_DX_MC_ALLOWED_$ROMO_$YYYYMM AS DA
ON ME.UNIQ_PERSON_NUM = DA.MEMBER_ID
WHERE ME.PLAN_TYPE NOT IN ('IPDP','GPDP') 
AND ((ME.ELIG_START_DT >= $START_DATE AND ME.ELIG_START_DT <= $END_DATE )
	OR(ME.ELIG_END_DT >= $START_DATE AND ME.ELIG_END_DT <= $END_DATE )
	OR(ME.ELIG_START_DT <= $START_DATE AND ME.ELIG_END_DT >= $END_DATE )
	OR(ME.ELIG_START_DT <= $START_DATE AND ME.ELIG_END_DT BETWEEN $START_DATE AND $END_DATE)
	)
--LIMIT 1000000
; 

-----------------------------------------------

CREATE TEMP TABLE $SDM_MEDICARE_MEMBER_STAGE_2_$ROMO_$YYYYMM 
AS
SELECT MEMBER_ID, MAX(ELIG_START_DT) AS MAX_START_DATE 
FROM $SDM_MEDICARE_MEMBER_STAGE_$ROMO_$YYYYMM 
GROUP BY MEMBER_ID
;

-----------------------------------------------

CREATE TEMP TABLE $SDM_MEDICARE_MEMBER_STAGE_3_$ROMO_$YYYYMM
AS
SELECT DISTINCT A.MEMBER_ID, A.OREC, A.MEDICAID
FROM $SDM_MEDICARE_MEMBER_STAGE_$ROMO_$YYYYMM A
INNER JOIN $SDM_MEDICARE_MEMBER_STAGE_2_$ROMO_$YYYYMM B
ON A.MEMBER_ID = B.MEMBER_ID AND A.ELIG_START_DT = B.MAX_START_DATE

;

-----------------------------------------------

CREATE TEMP TABLE $SDM_MEDICARE_MEMBER_STAGE_4_$ROMO_$YYYYMM
AS
SELECT
ROW_NUMBER() OVER (ORDER BY A.MEMBER_ID) AS ID,
A.MEMBER_ID, A.MEMBER_GENDER_CD, A.DOB, 
SUM(A.MONTHS_ELIGIBLE) AS ELIG, 
A.ALLOWED,
B.MEDICAID,
B.OREC
FROM $SDM_MEDICARE_MEMBER_STAGE_$ROMO_$YYYYMM AS A
LEFT JOIN $SDM_MEDICARE_MEMBER_STAGE_3_$ROMO_$YYYYMM AS B
ON B.MEMBER_ID = A.MEMBER_ID
GROUP BY A.MEMBER_ID, A.MEMBER_GENDER_CD, A.DOB, A.ALLOWED, B.MEDICAID, B.OREC
;

-----------------------------------------------
CREATE TEMP TABLE MC_UNIQ_TABLE_$ROMO
AS
SELECT MEMBER_ID, MAX(ID) AS MAX_ID
FROM $SDM_MEDICARE_MEMBER_STAGE_4_$ROMO_$YYYYMM
GROUP BY MEMBER_ID
;
-----------------------------------------------

INSERT INTO $SDM_GROUPER_DXCG_MEDICARE_MEMBER_INPUT_$ROMO_$YYYYMM
(MEMBER_ID
       , GENDER
       , DATE_OF_BIRTH
       , ELIGIBLE_MONTHS
       , DIAGNOSIS_EXPENDITURE
       , MEDICAID_FLAG
       , OREC
) 
SELECT
A.MEMBER_ID, 
A.MEMBER_GENDER_CD, 
A.DOB, 
CASE WHEN A.ELIG = 0 THEN 1 ELSE A.ELIG END, 
TO_NUMBER(A.ALLOWED, '9999999.99'),
A.MEDICAID,
A.OREC
FROM $SDM_MEDICARE_MEMBER_STAGE_4_$ROMO_$YYYYMM A
INNER JOIN MC_UNIQ_TABLE_$ROMO B
ON A.MEMBER_ID = B.MEMBER_ID AND A.ID = B.MAX_ID
;