CREATE TEMP TABLE T1_MEDICARE_$ROMO
AS
SELECT 
ROW_NUMBER() OVER (ORDER BY A.MEMBER_ID) AS ID,
B.SUB_ID, B.PERSON_NUM, A.MEMBER_ID AS UNIQ_PERSON_NUM, B.HICN_NUM, B.FAMILY_LINK_ID, B.SUB_ALT_ID,
B.ALT_PERSON_NUM, B.MEMBER_BIRTH_DT, B.MEMBER_GENDER_CD, B.MEMBER_ADDRESS_CITY, 
B.MEMBER_ADDRESS_STATE, B.MEMBER_ADDRESS_ZIP_CD, B.MEMBER_STATE_CD, B.CAC_CD, B.PRODUCT_CATEGORY_CD,
B.PLAN_CD, B.PLAN_TYPE, B.PROV_IPA_PCP_ID, B.PROV_IPA_ID, B.MEMBER_ID, A.DOB, A."AGE", A.SEX,
A.MED_MBR_MONTHS, A.EXPEND1, A.MCAID, A.OREC, A.ELIGCAT, A.SCORE_AGEGNDY1_MED, A.SCORE_AGEGNDY2_MED,
A.SCORE_DXY1, A.SCORE_DXY2, A.RISK_DRIVER_1, A.RISK_DRIVER_1PCT, A.RISK_DRIVER_2, A.RISK_DRIVER_2PCT,
A.RISK_DRIVER_3, A.RISK_DRIVER_3PCT, A.RISK_DRIVER_4, A.RISK_DRIVER_4PCT, A.RISK_DRIVER_5, A.RISK_DRIVER_5PCT,
A.C_GROUP, A.CAT, B.ELIG_START_DT, B.ELIG_END_DT
FROM $SDM_GROUPER_DXCG_MEDICARE_OUTPUT_$ROMO_$YYYYMM A
LEFT JOIN ADH_SBX_ROSETTA..MEDICARE_ELIG_$YYYYM1$DD B --$YYYYMM$DD
ON A.MEMBER_ID = B.UNIQ_PERSON_NUM AND B.PRODUCT_CATEGORY_CD != 'D' AND B.PLAN_TYPE NOT IN ('IPDP','GPDP')
AND ((B.ELIG_START_DT  >= 	$START_DATE AND B.ELIG_START_DT <= 	$END_DATE )
	OR(B.ELIG_END_DT   >= 	$START_DATE AND B.ELIG_END_DT   <= 	$END_DATE )
	OR(B.ELIG_START_DT <= 	$START_DATE AND B.ELIG_END_DT   >= 	$END_DATE )
	OR(B.ELIG_START_DT <= 	$START_DATE AND B.ELIG_END_DT BETWEEN $START_DATE AND $END_DATE)
	)	
;
---------------------------------------------------------------------------------------------------
CREATE TEMP TABLE T2_MEDICARE_$ROMO
AS
SELECT MEMBER_ID,MAX(ELIG_END_DT) AS ELIG_END, MAX(ID) AS MAXID
FROM T1_MEDICARE_$ROMO
GROUP BY MEMBER_ID
;
---------------------------------------------------------------------------------------------------
CREATE TABLE DXCG43_MEDICARE_$ROMO_$YYYYMM
AS
SELECT  SUB_ID,  PERSON_NUM, UNIQ_PERSON_NUM,  HICN_NUM,  FAMILY_LINK_ID,  SUB_ALT_ID,
 ALT_PERSON_NUM,  MEMBER_BIRTH_DT,  MEMBER_GENDER_CD,  MEMBER_ADDRESS_CITY, 
 MEMBER_ADDRESS_STATE,  MEMBER_ADDRESS_ZIP_CD,  MEMBER_STATE_CD,  CAC_CD,  PRODUCT_CATEGORY_CD,
 PLAN_CD,  PLAN_TYPE,  PROV_IPA_PCP_ID,  PROV_IPA_ID,  T1_MEDICARE_$ROMO.MEMBER_ID,  DOB,  "AGE",  SEX,
 MED_MBR_MONTHS,  EXPEND1,  MCAID,  OREC,  ELIGCAT,  SCORE_AGEGNDY1_MED,  SCORE_AGEGNDY2_MED,
 SCORE_DXY1,  SCORE_DXY2,  RISK_DRIVER_1,  RISK_DRIVER_1PCT,  RISK_DRIVER_2,  RISK_DRIVER_2PCT,
 RISK_DRIVER_3,  RISK_DRIVER_3PCT,  RISK_DRIVER_4,  RISK_DRIVER_4PCT,  RISK_DRIVER_5,  RISK_DRIVER_5PCT,
 C_GROUP,  CAT, TO_CHAR(T2_MEDICARE_$ROMO.ELIG_END,'YYYYMM') AS YR_MO, 
 CASE WHEN TO_CHAR(T2_MEDICARE_$ROMO.ELIG_END,'YYYYMM') >= '$YYYYMM' THEN 'Y' 
 ELSE 'N' END AS CURMBR
FROM T1_MEDICARE_$ROMO
INNER JOIN T2_MEDICARE_$ROMO
ON T1_MEDICARE_$ROMO.ID = T2_MEDICARE_$ROMO.MAXID
------------------------------------------------
